// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zql8MbaZgiTA4VRcAneswBUiYNCt7e8',
    appId: '1:133380734405:web:8ca3ed48da2282937c1fac',
    messagingSenderId: '133380734405',
    projectId: 'dashboard-725c9',
    authDomain: 'dashboard-725c9.firebaseapp.com',
    storageBucket: 'dashboard-725c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNbGU0SJ16eLDdHEQ49-Q3wfr9mEpK7gM',
    appId: '1:133380734405:android:7bc2ea6dbf4a2f467c1fac',
    messagingSenderId: '133380734405',
    projectId: 'dashboard-725c9',
    storageBucket: 'dashboard-725c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4o5zKU9PhMklrKtzFNvAf0POvfWXe7M',
    appId: '1:133380734405:ios:636948ea808979557c1fac',
    messagingSenderId: '133380734405',
    projectId: 'dashboard-725c9',
    storageBucket: 'dashboard-725c9.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );
}
